### PR TITLE
Allow for custom yum repositories specified in attribute hash

### PR DESCRIPTION
**Pull request by scotthain**
@opscode-cookbooks/engineering-services

### CODE REVIEW

**Comment by schisamo** [comment]
So dumb question...why would this not be configured in a wrapper of this cookbook like opscode-ci? Not sure I see the reason for the attribute-driven configuration.

**Comment by scotthain** [comment]
@schisamo I'm open to that, I'm not sure exactly what that would look like though. Can you point me at an example and we can discuss more? I was following the example in the _build_support recipe in opscode-ci. I put the empty config here for documentation purposes. (Unless I'm missing your meaning?)

**Comment by schisamo** [comment]
@scotthain Right now we set up things like base repos in `opscode-ci::_platform_tweaks`:
https://github.com/opscode-cookbooks/opscode-ci/blob/master/recipes/_platform_tweaks.rb#L57-L77

This approach would require no changes to this cookbook. It also follows the idioms we use for other types of configuration like this. Basically this cookbook should not be concerned with how a user chooses to configure things like repos.

**Comment by scotthain** [comment]
@schisamo I see it now, looks good. I'll move the repo additions to opscode-ci.

**Pull request closed without merging**
