### PR TITLE
Ship our own version of cacerts

### PR DESCRIPTION
**Pull request by thommay**
Rather than used the cached version, use an up to date one with the
verisign 1024 bit certs reapplied, so that ruby can hit s3 properly.
Without this change rubygems on Windows fails.

### CODE REVIEW

**Comment by schisamo** [comment]
@thommay Can we just point at the update cert from the cache?

**Comment by thommay** [comment]
Nope, they don't contain the old verisign certs. So either we need to do some extreme monkeying around to get the cached file direct over http, apply the certs and then do a file with contents, or we do this...

**Comment by schisamo** [comment]
@thommay I wonder if we should just take an approach similar to what you did in: https://github.com/chef/omnibus-software/commit/a714be43a973a3b07f5cf7ef23f2c43e670e3536 so everything is consistent. So we would fetch the certs from our S3 cache and then append the verisign certs on the end of the fetched file.

**Comment by thommay** [comment]
@schisamo we could, but i don't think it's worth the bother - the S3 certs only have another month or so to live IIRC.

**Comment by schisamo** [comment]
@thommay roger that. Let's get Travis happy and then get this rebased and merged then.

**Comment by thommay** [comment]
@schisamo rebased and travis'd!

**Pull request merged**
