### PR TITLE
Update for new url

### PR DESCRIPTION
**Pull request by oferrigni**

### CODE REVIEW

**Comment by yzl** [comment]
lgtm

**Comment by oferrigni** [comment]
Travis failed because 1.9 is no longer supported with the version of ohai

**Comment by schisamo** [comment]
@oferrigni Thx for the fix! A few of things:

* Perhaps we should [use this URL](http://rsync.samba.org/ftp/ccache/ccache-3.1.9.tar.gz) so the base matches the [location we download rsync from](https://github.com/opscode-cookbooks/omnibus/blob/v2.5.1/recipes/_rsync.rb#L32):

```
➜  curl -I "http://rsync.samba.org/ftp/ccache/ccache-3.1.9.tar.gz"
HTTP/1.1 200 OK
Date: Thu, 05 Feb 2015 11:07:42 GMT
Server: Apache/2.4.7
Strict-Transport-Security: max-age=15552000; includeSubDomains;preload
Last-Modified: Sun, 06 Jan 2013 17:03:06 GMT
ETag: "107a01e-55e01-4d2a1afb0a680"
Accept-Ranges: bytes
Content-Length: 351745
Content-Type: application/x-gzip
Content-Encoding: x-gzip
```

* Let's be sure to squash all commits related to updating the URL and put an in-depth message on the commit and PR so our future selves knows why this change was required.
* Go ahead and [remove Ruby 1.9 and Ruby 2.0 from the `.travis.yml`](https://github.com/opscode-cookbooks/omnibus/blob/v2.5.1/.travis.yml#L2-L3). We don't need to test against these versions of Ruby any longer now that [Chef ships with Ruby 2.1+](https://github.com/chef/omnibus-chef/blob/chef-12.0.3/config/projects/chef.rb#L54).

**Comment by oferrigni** [comment]
That url times out for me... I'll go ahead and fix up the other bits of the PR.

**Comment by schisamo** [comment]
@oferrigni If that URL is timing out it means the rsync download will most likely fail later on in the chef run:
https://github.com/opscode-cookbooks/omnibus/blob/v2.5.1/recipes/_rsync.rb#L32

Can we use the same mirror to grab rsync also?

**Comment by oferrigni** [comment]
PR updated accordingly

**Comment by stevendanna** [comment]
:+1: looks good to me.

**Comment by schisamo** [comment]
:shipit:

**Pull request merged**
