### PR TITLE
File::ALT_SEPARATOR isn't always a string

### PR DESCRIPTION
**Pull request by thommay**
This causes chefspec failures in certain situations

### CODE REVIEW

**Comment by schisamo** [comment]
:+1:

**Comment by sethvargo** [comment]
It's always defined, but sometimes it's defined as "nil" :smile:. Otherwise you'd have to check if the const_defined?, but other than that, :+1:

**Comment by thommay** [comment]
uh, sorry. yes :)

**Comment by thommay** [comment]
@sethvargo i fixed the title in the interests of accuracy

**Comment by sethvargo** [comment]
Well technically I was more picky about the commit message itself, but it's honestly fine :smile:. The spirit is there :+1:

**Comment by yzl** [comment]
:+1:

**Comment by scotthain** [comment]
:+1:

**Comment by thommay** [comment]
@sethvargo heh i dun fixed that too :blush:

**Comment by ksubrama** [comment]
All the :+1:

**Pull request merged**
